version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-estate
    ports:
      - "8800:8800"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-estate
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-estate
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge